### ISSUE TITLE
added mass implementation

### ISSUE THREAD

**Issue by TheChikenfly** [ONSAS/ONSAS#531]
If the added mass effect is not neglectable (like in water) the dynamics is different and this is not taken account by the model.
Maybe try to add added mass as an external force and use the expression for slender strucctures ?
![image](https://user-images.githubusercontent.com/100605156/185966127-8bf2eed6-2220-44d8-8e52-9dd059616703.png)

**Comment by jorgepz** [comment]
excellent! seems a very good idea. we can discuss this on wednesday!

**Comment by mvanzulli** [comment]
The coefficient `c_m` or mass ratio can be included into the [elements.elemTypeAero](https://onsas.github.io/ONSAS.m/dev/howtouse/creatingModels/#elements.elemTypeAero) struct.

**Comment by jorgepz** [comment]
i linked the PR of @TheChikenfly contribution to this issue. 
i think @mvanzulli idea for including the massRatio field is a good one. i would call the field `addedMassRatio`

**Comment by TheChikenfly** [comment]
> The coefficient `c_m` or mass ratio can be included into the [elements.elemTypeAero](https://onsas.github.io/ONSAS.m/dev/howtouse/creatingModels/#elements.elemTypeAero) struct, like:
> 
> ```matlab
> elements(2).elemTypeAero   = [0 d 0 numGaussPoints computeAeroTangentMatrix c_m ] ;
> ```
> 
> or we can include leafs into the elemTypeAero like:
> 
> ```matlab
> elements(2).elemTypeAero.chordVector = [ 0 d 0]
> elements(2).elemTypeAero.massRatio = c_m
> .
> .
> .
> ```

I agree it would be the best way to access the mass ratio! 
However maybe c_m is not the best name as in the litterature it often refers to cm=1+ca (ca is the added mass coefficient), maybe something like c_mr?

**Comment by jorgepz** [comment]
We re open the issue to add validation test in the CI.

**Comment by jorgepz** [comment]
the current version is having a convergence issue in the second analysis case of the example.

**Comment by jorgepz** [comment]
it seems that the problem is related to a udotflow zero at the very beginning and an infinite reynolds number that breaks everything... i'll be on it in following days... probably i'll need to slightly change the example

**Comment by jorgepz** [comment]
related to https://github.com/ONSAS/ONSAS/issues/617

**Comment by mvanzulli** [comment]
> Hi @TheChikenfly I am in a meeting with @mvanzulli and we do not recall where the expression in
> 
> https://github.com/ONSAS/ONSAS/blob/19a0af6a624f7689467e93086b70700412e5baf9/examples/addedMassPendulum/addedMassPendulum.m#L131
> was taken from. do you recall for which case was this valid? thanks

However, we managed to solve the convergence issue by using $C_d = 1.2$

**Comment by jorgepz** [comment]
the added mass example considers a still fluid. however in https://github.com/ONSAS/ONSAS/blob/master/src/elements/frame/addedMassForce.m the added mass force is computed using the fluid acceleration...

**Comment by jorgepz** [comment]
Thanks @mvanzulli . The example is already being simplified to ease the testing and debugging, in my branch you can see the new version (in process) . one of the plots I am getting is 
![image](https://github.com/ONSAS/ONSAS/assets/42485529/9b078cf9-d04c-498a-b6a8-81d050dca1f7) where it can be seen that there is mass missing... the red line is the analytic and the blue the numerical.

at least @TheChikenfly corrects us, it seems that in the current version of ONSAS the added mass is NOT considering the acceleration of the solid.

It would be useful to have a date or commit related to the ONSAS version that Alexandre used in the examples.

This seems to stay in stand by until we get updates. I will merge the PR https://github.com/ONSAS/ONSAS/pull/678 so that other changes get to master
